remote_theme: just-the-docs/just-the-docs
title: NiceNotes
description: Projekt von Nikolas Teuber für die Veranstaltung Wi-Inf-M09 
mermaid:
  version: "9.4.3" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: 🤍 Tip
    color: purple
  info:
    title: ℹ️ Info
    color: blue
  attention:
    title: ❕ Attention
    color: yellow

