remote_theme: just-the-docs/just-the-docs
title: NiceNotes
description: Projekt von Nikolas Teuber für die Veranstaltung Wi-Inf-M09 
mermaid:
  version: "9.4.3" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: 🤍 Tip
    color: purple
  info:
    title: ℹ️ Info
    color: blue
  attention:
    title: ❕ Attention
    color: yellow
sidebar:
  - title: Value Proposition
    url: /docs/value-proposition/
  - title: Technical Docs
    output: web
    folderitems:
      - title: App Structure
        url: /Technical Docs/: App Structure
      - title: App Behavior
        url: /Technical Docs/: App Behavior
      - title: Data Model
        url: /Technical Docs/: Data Model
      - title: API Reference
        url: /Technical Docs/: API Reference
      - title: Design Decisions
        url: /Technical Docs/: Design Decisions
  - title: User evaluation
    url: /docs/user-evaluation/
  - title: Goals achieved and missed
    url: /docs/goals-achieved-and-missed/
  - title: What I would improve in the future
    url: /docs/what-I-would-improve-in-the-future/
  - title: Peer review
    url: /docs/peer-review/
